create database HVTSchoolDBdemo
go
create table USERS(
USER_NAME nvarchar(50) primary key,
PASS_WORD nvarchar(50) NOT NULL,
ROLE_ID int ,
CLASS_ID_OFUSER int,
[FULL_NAME] nvarchar(50),
PHONE nvarchar(20),
EMAIL nvarchar(50),
)

go
create table ROLES(
ROLE_ID int IDENTITY(1,1) primary key,
ROLE_NAME nvarchar(50) NOT NULL
)

go
create table CLASSES(
CLASS_ID int IDENTITY(1,1) primary key,
GRADE int NOT NULL,
GIFTED_CLASS nvarchar(50) NOT NULL,
CONSTRAINT UC_CLASS UNIQUE (GRADE,GIFTED_CLASS)
)
GO
create table TEACHERS(
TEARCHER_ID int IDENTITY(1,1) primary key,
[FULL_NAME] nvarchar(50) NOT NULL,
PHONE nvarchar(20),
EMAIL nvarchar(50),
MAPPING_NAME nvarchar(20) NOT NULL UNIQUE
)
go
create table MAIN_TEACHER_CLASSES(
CLASS_ID int NOT NULL,
TEACHER_ID int NOT NULL,
DATE_FROM date
PRIMARY KEY (CLASS_ID,TEACHER_ID)
)
go
create table TIMETABLES(
TEARCHER_ID int NOT NULL,
CLASS_ID int NOT NULL,
SLOT int NOT NULL,
[DAY] nvarchar(50) NOT NULL,
[SUBJECT] nvarchar(50) NOT NULL,
APPLY_FROM date NOT NULL UNIQUE,
PRIMARY KEY (TEARCHER_ID,CLASS_ID)
)
go
create table CLASS_RED_STARS(
CLASS_ID int NOT NULL,
RED_STAR nvarchar(50) NOT NULL,
SCHOOL_WEEK_ID int NOT NULL,
PRIMARY KEY(CLASS_ID,RED_STAR,SCHOOL_WEEK_ID)
)

go
create table VIOLATIONS(
VIOLATION_ID int IDENTITY(1,1) primary key,
[NAME] nvarchar(50),
[DESCRIPTION] nvarchar(255),
SUBSTRACT_GRADE float NOT NULL
)
go
create table VIOLATION_CLASSES(
CLASS_ID int NOT NULL,
VIOLATION_ID int NOT NULL,
SCHOOL_WEEK_ID int NOT NULL,
[DAY] nvarchar(50) NOT NULL,
[DATE] date,
QUANTITY int NOT NULL,
NOTE nvarchar(255),
[STATUS] INT,
PRIMARY KEY(CLASS_ID,VIOLATION_ID,SCHOOL_WEEK_ID,[DAY])
)

go
create table VIOLATION_CLASS_RESQUESTS(
CLASS_ID int NOT NULL,
VIOLATION_ID int NOT NULL,
SCHOOL_WEEK_ID int NOT NULL,
[DAY] nvarchar(50) NOT NULL,
[DATE] date,
QUANTITY int NOT NULL,
REASON nvarchar(255),
NOTE nvarchar(255),
STT_CHANGE int,
FROM_USER nvarchar(50) NOT NULL,
ROLE_FROM_USER int ,
PRIMARY KEY(CLASS_ID,VIOLATION_ID,SCHOOL_WEEK_ID,[DAY])
)

go
create table SCHOOL_YEARS(
SCHOOL_YEAR_ID int IDENTITY(1,1) primary key,
FROM_DATE date,
TO_DATE date,
CONSTRAINT UC_YEARS UNIQUE (FROM_DATE,TO_DATE)
)
go
create table SCHOOL_SEMESTERS(
SCHOOL_SEMESTER_ID int IDENTITY(1,1) primary key,
SCHOOL_YEAR_ID int NOT NULL,
SEMESTER INT NOT NULL,
CONSTRAINT UC_SEMESTERS UNIQUE (SCHOOL_YEAR_ID,SEMESTER)
)

go
create table SCHOOL_MONTHS(
SCHOOL_MONTH_ID int IDENTITY(1,1) primary key,
SCHOOL_SEMESTER_ID int NOT NULL,
[MONTH] int NOT NULL,
CONSTRAINT UC_MONTHS UNIQUE (SCHOOL_SEMESTER_ID,[MONTH])
)

go
create table SCHOOL_WEEKS(
SCHOOL_WEEK_ID int IDENTITY(1,1) primary key,
SCHOOL_MONTH_ID int NOT NULL,
[WEEK] int NOT NULL,
FROM_DATE date,
TO_DATE date,
CONSTRAINT UC_WEEKS UNIQUE (SCHOOL_MONTH_ID,[WEEK])
)

go
create table SCHOOL_RANK_YEARS(
SCHOOL_YEAR_ID int NOT NULL,
CLASS_ID int NOT NULL,
[RANK] int,
PRIMARY KEY(SCHOOL_YEAR_ID,CLASS_ID)
)

go
create table SCHOOL_RANK_SEMESTERS(
SCHOOL_SEMESTER_ID int NOT NULL,
CLASS_ID int NOT NULL,
[RANK] int,
PRIMARY KEY(SCHOOL_SEMESTER_ID,CLASS_ID)
)

go
create table SCHOOL_RANK_MONTHS(
SCHOOL_MONTH_ID int NOT NULL,
CLASS_ID int NOT NULL,
[RANK] int ,
PRIMARY KEY(SCHOOL_MONTH_ID,CLASS_ID)
)
GO
create table SCHOOL_RANK_WEELS(
SCHOOL_WEEK_ID int NOT NULL,
CLASS_ID int NOT NULL,
[RANK] int, 
TOTAL_GRADE float,
PRIMARY KEY(SCHOOL_WEEK_ID,CLASS_ID)
)

go
CREATE table NEWSLETTERS(
NEWSLETTER_ID int primary key,
FROM_USER nvarchar(50),
ROLE_FROM_USER int,
HEADER nvarchar(255),
CONTENT nvarchar(max),
[IMAGE] image,
[STATUS] INT,
)
go
create table VIOLATION_ENTERING_TIME(
ROLE_ID int NOT NULL,
START_TIME time NOT NULL,
END_TIME time NOT NULL,
PRIMARY KEY(ROLE_ID,START_TIME,END_TIME)
)