
create database HVTSchoolDB 
go
use HVTSchoolDB
go
create table USERS(
USER_NAME nvarchar(30) primary key,
PASS_WORD nvarchar(50),
CLASS nvarchar(25),
[NAME] nvarchar(50),
PHONE nvarchar(15),
EMAIL nvarchar(50)
)

go
create table ROLES(
ROLE_ID int primary key,
ROLE_NAME nvarchar(25)
)

go
create table USER_ROLES(
[USER_NAME] nvarchar(30) REFERENCES USERS(USER_NAME),
ROLE_ID int REFERENCES ROLES(ROLE_ID),
)
go
create table NEWSLETTERS(
NEWSLETTER_ID int primary key,
FROM_USER nvarchar(30) REFERENCES USERS(USER_NAME),
ROLE_FROM_USER int REFERENCES ROLES(ROLE_ID),
HEADER nvarchar(100),
CONTENT nvarchar(max),
[IMAGE] image,
[STATUS] bit,
)
go
create table VIOLATION_ENTERING_TIME(
ROLE_ID int REFERENCES ROLES(ROLE_ID),
START_TIME time,
END_TIME time,
PRIMARY KEY(ROLE_ID,START_TIME,END_TIME)
)
go
create table CLASSES(
CLASS_ID int primary key,
GRADE int,
GIFTED_CLASS nvarchar(50)
)
go
create table CLASS_RED_STARS(
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
RED_STAR nvarchar(30) REFERENCES USERS(USER_NAME),
DATE_F date,
DATE_T date,
PRIMARY KEY(CLASS_ID,RED_STAR)
)
go
create table TEACHERS(
TEARCHER_ID int primary key,
[NAME] nvarchar(60),
PHONE nvarchar(15),
EMAIL nvarchar(60),?MAPPING_NAME nvarchar(15)
)
go
create table MAIN_TEACHER_CLASSES(
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
TEACHER_ID int REFERENCES TEACHERS(TEARCHER_ID),
DATE_FROM date
)
go
create table TIMETABLES(
TEARCHER_ID int REFERENCES TEACHERS(TEARCHER_ID),
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
SLOT int,
[DAY] nvarchar(50),
[SUBJECT] nvarchar(30),
APPLY_FROM date
)
go
create table VIOLATIONS(
VIOLATION_ID int primary key,
[NAME] nvarchar(50),
[DESCRIPTION] nvarchar(100),
SUBSTRACT_GRADE float
)
go
create table SCHOOL_YEARS(
SCHOOL_YEAR_ID int IDENTITY(1,1) primary key,
FROM_DATE date,
TO_DATE date
)
go
create table SCHOOL_SEMESTERS(
SCHOOL_SEMESTER_ID int IDENTITY(1,1) primary key,
SCHOOL_YEAR_ID int REFERENCES SCHOOL_YEARS(SCHOOL_YEAR_ID),
SEMESTER nvarchar(30),
)

go
create table SCHOOL_MONTHS(
SCHOOL_MONTH_ID int IDENTITY(1,1) primary key,
SCHOOL_SEMESTER_ID int REFERENCES SCHOOL_SEMESTERS(SCHOOL_SEMESTER_ID),
[MONTH] int,
)

go
create table SCHOOL_WEEKS(
SCHOOL_WEEK_ID int IDENTITY(1,1) primary key,
SCHOOL_MONTH_ID int REFERENCES SCHOOL_MONTHS(SCHOOL_MONTH_ID),
[WEEK] int,
FROM_DATE date,
TO_DATE date,
)

go
create table SCHOOL_RANK_WEELS(
SCHOOL_WEEK_ID int IDENTITY(1,1) REFERENCES SCHOOL_WEEKS(SCHOOL_WEEK_ID),
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
[RANK] int, 
TOTAL_GRADE float
)

go
create table VIOLATION_CLASSES(
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
VIOLATION_ID int REFERENCES VIOLATIONS(VIOLATION_ID),
SCHOOL_WEEK_ID int IDENTITY(1,1) REFERENCES SCHOOL_WEEKS(SCHOOL_WEEK_ID),
[DAY] nvarchar(50),
[DATE] date,
QUANTITY int,
NOTE nvarchar(1000),
[STATUS] bit,
PRIMARY KEY(CLASS_ID,VIOLATION_ID,SCHOOL_WEEK_ID,DAY)
)

go
create table VIOLATION_CLASS_RESQUESTS(
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
VIOLATION_ID int REFERENCES VIOLATIONS(VIOLATION_ID),
SCHOOL_WEEK_ID int REFERENCES SCHOOL_WEEKS(SCHOOL_WEEK_ID),
[DAY] nvarchar(50),
[DATE] date,
QUANTITY int,
REASON nvarchar(1000),
NOTE nvarchar(1000),
STT_CHANGE int,
FROM_USER nvarchar(30) REFERENCES USERS(USER_NAME),
ROLE_FROM_USER int REFERENCES ROLES(ROLE_ID),
PRIMARY KEY(CLASS_ID,VIOLATION_ID,SCHOOL_WEEK_ID,DAY)
)

go
create table SCHOOL_RANK_YEARS(
SCHOOL_YEAR_ID int REFERENCES SCHOOL_YEARS(SCHOOL_YEAR_ID),
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
[RANK] int
)

go
create table SCHOOL_RANK_SEMESTERS(
SCHOOL_SEMESTER_ID int REFERENCES SCHOOL_SEMESTERS(SCHOOL_SEMESTER_ID),
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
[RANK] int
)

go
create table SCHOOL_RANK_MONTHS(
SCHOOL_MONTH_ID int REFERENCES SCHOOL_MONTHS(SCHOOL_MONTH_ID),
CLASS_ID int REFERENCES CLASSES(CLASS_ID),
[RANK] int 
)



